# netlify.toml
[build]
  # The command that builds your project
  command = "dx bundle --release"
  # The directory to publish (upload) to Netlify
  publish = "target/dx/stickyexplorer/release/web/public"